In [49]:
# Import Library
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.ensemble import RandomForestClassifier

In [50]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [51]:
df = pd.read_csv('drive/MyDrive/MPL Analitics/MPL Draft Pick.csv')
df

,Match ID,Blue Team,Blue Team EXP Laner,Blue Team Jungler,Blue Team Midlaner,Blue Team Gold Laner,Blue Team Roamer,Red Team,Red Team EXP Laner,Red Team Jungler,Red Team Midlaner,Red Team Gold Laner,Red Team Roamer,Winner
0,MPLID_S14_GRP_W1_D1_M1_G1,Team Liquid ID,Edith,Julian,Luo Yi,Moskov,Minotaur,Fnatic Onic,Arlott,Roger,Valentina,Harith,Chou,0
1,MPLID_S14_GRP_W1_D1_M1_G2,Fnatic Onic,Thamuz,Nolan,Va;entina,Harith,Minotaur,Team Liquid ID,Arlott,Joy,Vexana,Roger,Edith,1
2,MPLID_S14_GRP_W1_D1_M2_G1,Dewa United Esport,Hylos,Julian,Valentina,Claude,Edith,EVOS Glory,Ruby,Nolan,Vexana,Moskov,Khufra,1
3,MPLID_S14_GRP_W1_D1_M2_G2,Dewa United Esport,X.Borg,Julian,Valentina,Moskov,Arlott,EVOS Glory,Hylos,Roger,Zask,Claude,Guinevere,0
4,MPLID_S14_GRP_W1_D1_M2_G3,Dewa United Esport,Paquito,Julian,Valentina,Moskov,Hylos,EVOS Glory,X.Borg,Roger,Novaria,Harith,Guinevere,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,MPLID_S14_GRAND_FNL_D1_M1_G3,Team Liquid ID,Benedetta,Alpha,Yve,Natan,Chip,RRQ,Hilda,Bane,Zhuxin,Irithel,Gatotkaca,0
208,MPLID_S14_GRAND_FNL_D1_M1_G4,Team Liquid ID,Hylos,Suyou,Zhuxin,Beatrix,Khaleed,RRQ,Hilda,Bane,Aurora,Natan,Mathilda,1
209,MPLID_S14_GRAND_FNL_D1_M1_G5,RRQ,Phoveus,Bane,Zhuxin,Beatrix,Jawhead,Team Liquid ID,Khaleed,Alpha,Yve,Natan,Tigreal,1
210,MPLID_S14_GRAND_FNL_D1_M1_G6,Team Liquid ID,Phoveus,Ling,Angela,Lunox,Khaleed,RRQ,Barats,Julian,Faramis,Irithel,Mathilda,1
211,MPLID_S14_GRAND_FNL_D1_M1_G7,RRQ,Barats,Alpha,Faramis,Ixia,Mathilda,Team Liquid ID,Terizla,Ling,Angela,Harith,Chou,0

In [52]:
df.columns

Index(['Match ID', 'Blue Team', 'Blue Team EXP Laner', 'Blue Team Jungler',
       'Blue Team Midlaner', 'Blue Team Gold Laner', 'Blue Team Roamer',
       'Red Team', 'Red Team EXP Laner', 'Red Team Jungler',
       'Red Team Midlaner', 'Red Team Gold Laner', 'Red Team Roamer',
       'Winner'],
      dtype='object')

In [53]:
df['Blue Team'].value_counts()

Blue Team
Team Liquid ID        31
Bigetron Alpha        28
Geek Fam ID           26
RRQ                   23
RBL                   23
Alter Ego             23
Fnatic Onic           21
EVOS Glory            20
Dewa United Esport    17
Name: count, dtype: int64

In [54]:
df['Red Team'].value_counts()

Red Team
RRQ                   32
Team Liquid ID        28
Geek Fam ID           27
Bigetron Alpha        26
Fnatic Onic           22
Dewa United Esport    22
EVOS Glory            21
Alter Ego             18
RBL                   16
Name: count, dtype: int64

In [55]:
df['Winner'].value_counts()

Winner
0    106
1    106
Name: count, dtype: int64

In [56]:
# Definisikan kolom hero pick
blue_team_roles = ["Blue Team EXP Laner", "Blue Team Jungler", "Blue Team Midlaner",
                   "Blue Team Gold Laner", "Blue Team Roamer"]
red_team_roles = ["Red Team EXP Laner", "Red Team Jungler", "Red Team Midlaner",
                  "Red Team Gold Laner", "Red Team Roamer"]

In [58]:
# Gabungkan semua hero yang dipilih dalam satu kolom
hero_columns = blue_team_roles + red_team_roles

# One-hot encoding semua hero
df_onehot = pd.get_dummies(df[hero_columns].stack()).groupby(level=0).sum()

In [60]:
df

,Match ID,Blue Team,Blue Team EXP Laner,Blue Team Jungler,Blue Team Midlaner,Blue Team Gold Laner,Blue Team Roamer,Red Team,Red Team EXP Laner,Red Team Jungler,Red Team Midlaner,Red Team Gold Laner,Red Team Roamer,Winner
0,MPLID_S14_GRP_W1_D1_M1_G1,Team Liquid ID,Edith,Julian,Luo Yi,Moskov,Minotaur,Fnatic Onic,Arlott,Roger,Valentina,Harith,Chou,0
1,MPLID_S14_GRP_W1_D1_M1_G2,Fnatic Onic,Thamuz,Nolan,Va;entina,Harith,Minotaur,Team Liquid ID,Arlott,Joy,Vexana,Roger,Edith,1
2,MPLID_S14_GRP_W1_D1_M2_G1,Dewa United Esport,Hylos,Julian,Valentina,Claude,Edith,EVOS Glory,Ruby,Nolan,Vexana,Moskov,Khufra,1
3,MPLID_S14_GRP_W1_D1_M2_G2,Dewa United Esport,X.Borg,Julian,Valentina,Moskov,Arlott,EVOS Glory,Hylos,Roger,Zask,Claude,Guinevere,0
4,MPLID_S14_GRP_W1_D1_M2_G3,Dewa United Esport,Paquito,Julian,Valentina,Moskov,Hylos,EVOS Glory,X.Borg,Roger,Novaria,Harith,Guinevere,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,MPLID_S14_GRAND_FNL_D1_M1_G3,Team Liquid ID,Benedetta,Alpha,Yve,Natan,Chip,RRQ,Hilda,Bane,Zhuxin,Irithel,Gatotkaca,0
208,MPLID_S14_GRAND_FNL_D1_M1_G4,Team Liquid ID,Hylos,Suyou,Zhuxin,Beatrix,Khaleed,RRQ,Hilda,Bane,Aurora,Natan,Mathilda,1
209,MPLID_S14_GRAND_FNL_D1_M1_G5,RRQ,Phoveus,Bane,Zhuxin,Beatrix,Jawhead,Team Liquid ID,Khaleed,Alpha,Yve,Natan,Tigreal,1
210,MPLID_S14_GRAND_FNL_D1_M1_G6,Team Liquid ID,Phoveus,Ling,Angela,Lunox,Khaleed,RRQ,Barats,Julian,Faramis,Irithel,Mathilda,1
211,MPLID_S14_GRAND_FNL_D1_M1_G7,RRQ,Barats,Alpha,Faramis,Ixia,Mathilda,Team Liquid ID,Terizla,Ling,Angela,Harith,Chou,0

In [ ]:
#file_path = '/content/drive/MyDrive/MPL Analitics/MPL_Draft_Pick.xlsx'
#df.to_excel(file_path, index=False)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Bagi data menjadi training dan testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inisialisasi dan latih model Random Forest
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Prediksi pada data uji
y_pred = model.predict(X_test)

# Evaluasi akurasi (mengukur berapa banyak hero lawan yang diprediksi dengan benar)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2%}")