In [314]:
import pandas as pd

In [315]:
df = pd.read_csv("Match MPL.csv")
df

,Match ID,Tanggal,Liga,Blue Team,Blue Team Heroes,Red Team,Red Team Heroes,Winner
0,MPLID_S14_GRP_W1_D1_M1_G1,08/09/2024,MPL Indonesia,Team Liquid ID,"Edith,Julian,Luo Yi,Moskov,Minotaur",Fnatic Onic,"Arlott,Roger,Valentina,Harith,Chou",Red Team
1,MPLID_S14_GRP_W1_D1_M1_G2,08/09/2024,MPL Indonesia,Fnatic Onic,"Thamuz,Nolan,Va;entina,Harith,Minotaur",Team Liquid ID,"Arlott,Joy,Vexana,Roger,Edith",Blue Team
2,MPLID_S14_GRP_W1_D1_M2_G1,08/09/2024,MPL Indonesia,Dewa United Esport,"Hylos,Julian,Valentina,Claude,Edith",EVOS Glory,"Ruby,Nolan,Vexana,Moskov,Khufra",Blue Team
3,MPLID_S14_GRP_W1_D1_M2_G2,08/09/2024,MPL Indonesia,Dewa United Esport,"X.Borg,Julian,Valentina,Moskov,Arlott",EVOS Glory,"Hylos,Roger,Zask,Claude,Guinevere",Red Team
4,MPLID_S14_GRP_W1_D1_M2_G3,08/09/2024,MPL Indonesia,Dewa United Esport,"Paquito,Julian,Valentina,Moskov,Hylos",EVOS Glory,"X.Borg,Roger,Novaria,Harith,Guinevere",Blue Team
...,...,...,...,...,...,...,...,...
207,MPLID_S14_GRAND_FNL_D1_M1_G3,10/27/2024,MPL Indonesia,Team Liquid ID,"Benedetta,Alpha,Yve,Natan,Chip",RRQ,"Hilda,Bane,Zhuxin,Irithel,Gatotkaca",Red Team
208,MPLID_S14_GRAND_FNL_D1_M1_G4,10/27/2024,MPL Indonesia,Team Liquid ID,"Hylos,Suyou,Zhuxin,Beatrix,Khaleed",RRQ,"Hilda,Bane,Aurora,Natan,Mathilda",Blue Team
209,MPLID_S14_GRAND_FNL_D1_M1_G5,10/27/2024,MPL Indonesia,RRQ,"Phoveus,Bane,Zhuxin,Beatrix,Jawhead",Team Liquid ID,"Khaleed,Alpha,Yve,Natan,Tigreal",Blue Team
210,MPLID_S14_GRAND_FNL_D1_M1_G6,10/27/2024,MPL Indonesia,Team Liquid ID,"Phoveus,Ling,Angela,Lunox,Khaleed",RRQ,"Barats,Julian,Faramis,Irithel,Mathilda",Blue Team
211,MPLID_S14_GRAND_FNL_D1_M1_G7,10/27/2024,MPL Indonesia,RRQ,"Barats,Alpha,Faramis,Ixia,Mathilda",Team Liquid ID,"Terizla,Ling,Angela,Harith,Chou",Red Team

In [316]:
df.columns

Index(['Match ID', 'Tanggal ', 'Liga', 'Blue Team', 'Blue Team Heroes',
       'Red Team', 'Red Team Heroes', 'Winner'],
      dtype='object')

In [317]:
df1 = pd.DataFrame(df, columns=["Match ID", "Blue Team","Blue Team Heroes","Red Team","Red Team Heroes", "Winner"])
df1

,Match ID,Blue Team,Blue Team Heroes,Red Team,Red Team Heroes,Winner
0,MPLID_S14_GRP_W1_D1_M1_G1,Team Liquid ID,"Edith,Julian,Luo Yi,Moskov,Minotaur",Fnatic Onic,"Arlott,Roger,Valentina,Harith,Chou",Red Team
1,MPLID_S14_GRP_W1_D1_M1_G2,Fnatic Onic,"Thamuz,Nolan,Va;entina,Harith,Minotaur",Team Liquid ID,"Arlott,Joy,Vexana,Roger,Edith",Blue Team
2,MPLID_S14_GRP_W1_D1_M2_G1,Dewa United Esport,"Hylos,Julian,Valentina,Claude,Edith",EVOS Glory,"Ruby,Nolan,Vexana,Moskov,Khufra",Blue Team
3,MPLID_S14_GRP_W1_D1_M2_G2,Dewa United Esport,"X.Borg,Julian,Valentina,Moskov,Arlott",EVOS Glory,"Hylos,Roger,Zask,Claude,Guinevere",Red Team
4,MPLID_S14_GRP_W1_D1_M2_G3,Dewa United Esport,"Paquito,Julian,Valentina,Moskov,Hylos",EVOS Glory,"X.Borg,Roger,Novaria,Harith,Guinevere",Blue Team
...,...,...,...,...,...,...
207,MPLID_S14_GRAND_FNL_D1_M1_G3,Team Liquid ID,"Benedetta,Alpha,Yve,Natan,Chip",RRQ,"Hilda,Bane,Zhuxin,Irithel,Gatotkaca",Red Team
208,MPLID_S14_GRAND_FNL_D1_M1_G4,Team Liquid ID,"Hylos,Suyou,Zhuxin,Beatrix,Khaleed",RRQ,"Hilda,Bane,Aurora,Natan,Mathilda",Blue Team
209,MPLID_S14_GRAND_FNL_D1_M1_G5,RRQ,"Phoveus,Bane,Zhuxin,Beatrix,Jawhead",Team Liquid ID,"Khaleed,Alpha,Yve,Natan,Tigreal",Blue Team
210,MPLID_S14_GRAND_FNL_D1_M1_G6,Team Liquid ID,"Phoveus,Ling,Angela,Lunox,Khaleed",RRQ,"Barats,Julian,Faramis,Irithel,Mathilda",Blue Team
211,MPLID_S14_GRAND_FNL_D1_M1_G7,RRQ,"Barats,Alpha,Faramis,Ixia,Mathilda",Team Liquid ID,"Terizla,Ling,Angela,Harith,Chou",Red Team

In [318]:
df2 = pd.DataFrame(df1)
df2.rename(columns={'Blue Team Heroes': 'Blue Team EXP Laner'}, inplace=True)
df2.insert(3, 'Blue Team Jungler', 0)
df2.insert(4, 'Blue Team Midlaner', 0)
df2.insert(5, 'Blue Team Gold Laner', 0)
df2.insert(6, 'Blue Team Roamer', 0)
df2

,Match ID,Blue Team,Blue Team EXP Laner,Blue Team Jungler,Blue Team Midlaner,Blue Team Gold Laner,Blue Team Roamer,Red Team,Red Team Heroes,Winner
0,MPLID_S14_GRP_W1_D1_M1_G1,Team Liquid ID,"Edith,Julian,Luo Yi,Moskov,Minotaur",0,0,0,0,Fnatic Onic,"Arlott,Roger,Valentina,Harith,Chou",Red Team
1,MPLID_S14_GRP_W1_D1_M1_G2,Fnatic Onic,"Thamuz,Nolan,Va;entina,Harith,Minotaur",0,0,0,0,Team Liquid ID,"Arlott,Joy,Vexana,Roger,Edith",Blue Team
2,MPLID_S14_GRP_W1_D1_M2_G1,Dewa United Esport,"Hylos,Julian,Valentina,Claude,Edith",0,0,0,0,EVOS Glory,"Ruby,Nolan,Vexana,Moskov,Khufra",Blue Team
3,MPLID_S14_GRP_W1_D1_M2_G2,Dewa United Esport,"X.Borg,Julian,Valentina,Moskov,Arlott",0,0,0,0,EVOS Glory,"Hylos,Roger,Zask,Claude,Guinevere",Red Team
4,MPLID_S14_GRP_W1_D1_M2_G3,Dewa United Esport,"Paquito,Julian,Valentina,Moskov,Hylos",0,0,0,0,EVOS Glory,"X.Borg,Roger,Novaria,Harith,Guinevere",Blue Team
...,...,...,...,...,...,...,...,...,...,...
207,MPLID_S14_GRAND_FNL_D1_M1_G3,Team Liquid ID,"Benedetta,Alpha,Yve,Natan,Chip",0,0,0,0,RRQ,"Hilda,Bane,Zhuxin,Irithel,Gatotkaca",Red Team
208,MPLID_S14_GRAND_FNL_D1_M1_G4,Team Liquid ID,"Hylos,Suyou,Zhuxin,Beatrix,Khaleed",0,0,0,0,RRQ,"Hilda,Bane,Aurora,Natan,Mathilda",Blue Team
209,MPLID_S14_GRAND_FNL_D1_M1_G5,RRQ,"Phoveus,Bane,Zhuxin,Beatrix,Jawhead",0,0,0,0,Team Liquid ID,"Khaleed,Alpha,Yve,Natan,Tigreal",Blue Team
210,MPLID_S14_GRAND_FNL_D1_M1_G6,Team Liquid ID,"Phoveus,Ling,Angela,Lunox,Khaleed",0,0,0,0,RRQ,"Barats,Julian,Faramis,Irithel,Mathilda",Blue Team
211,MPLID_S14_GRAND_FNL_D1_M1_G7,RRQ,"Barats,Alpha,Faramis,Ixia,Mathilda",0,0,0,0,Team Liquid ID,"Terizla,Ling,Angela,Harith,Chou",Red Team

In [319]:
#loop for each row, adding heroes to new columns

df3 = pd.DataFrame(df2)

#change result column to 1 and 0. 1 means winning, 0 means losing
for i in range(len(df3)): 
    if (df3.loc[i,'Winner'] == "Blue Team"):
        df3.loc[i,'Winner'] = 1
    elif (df3.loc[i,'Winner'] == "Red Team"):
        df3.loc[i,'Winner'] = 0
        
    data=df3.loc[i,'Blue Team EXP Laner']
    data=data.split(",")
    
    df3.loc[i,'Blue Team EXP Laner']=data[0].strip()
    df3.loc[i,'Blue Team Jungler']=data[1].strip()
    df3.loc[i,'Blue Team Midlaner']=data[2].strip()
    df3.loc[i,'Blue Team Gold Laner']=data[3].strip()
    df3.loc[i,'Blue Team Roamer']=data[4].strip()
    
df3

,Match ID,Blue Team,Blue Team EXP Laner,Blue Team Jungler,Blue Team Midlaner,Blue Team Gold Laner,Blue Team Roamer,Red Team,Red Team Heroes,Winner
0,MPLID_S14_GRP_W1_D1_M1_G1,Team Liquid ID,Edith,Julian,Luo Yi,Moskov,Minotaur,Fnatic Onic,"Arlott,Roger,Valentina,Harith,Chou",0
1,MPLID_S14_GRP_W1_D1_M1_G2,Fnatic Onic,Thamuz,Nolan,Va;entina,Harith,Minotaur,Team Liquid ID,"Arlott,Joy,Vexana,Roger,Edith",1
2,MPLID_S14_GRP_W1_D1_M2_G1,Dewa United Esport,Hylos,Julian,Valentina,Claude,Edith,EVOS Glory,"Ruby,Nolan,Vexana,Moskov,Khufra",1
3,MPLID_S14_GRP_W1_D1_M2_G2,Dewa United Esport,X.Borg,Julian,Valentina,Moskov,Arlott,EVOS Glory,"Hylos,Roger,Zask,Claude,Guinevere",0
4,MPLID_S14_GRP_W1_D1_M2_G3,Dewa United Esport,Paquito,Julian,Valentina,Moskov,Hylos,EVOS Glory,"X.Borg,Roger,Novaria,Harith,Guinevere",1
...,...,...,...,...,...,...,...,...,...,...
207,MPLID_S14_GRAND_FNL_D1_M1_G3,Team Liquid ID,Benedetta,Alpha,Yve,Natan,Chip,RRQ,"Hilda,Bane,Zhuxin,Irithel,Gatotkaca",0
208,MPLID_S14_GRAND_FNL_D1_M1_G4,Team Liquid ID,Hylos,Suyou,Zhuxin,Beatrix,Khaleed,RRQ,"Hilda,Bane,Aurora,Natan,Mathilda",1
209,MPLID_S14_GRAND_FNL_D1_M1_G5,RRQ,Phoveus,Bane,Zhuxin,Beatrix,Jawhead,Team Liquid ID,"Khaleed,Alpha,Yve,Natan,Tigreal",1
210,MPLID_S14_GRAND_FNL_D1_M1_G6,Team Liquid ID,Phoveus,Ling,Angela,Lunox,Khaleed,RRQ,"Barats,Julian,Faramis,Irithel,Mathilda",1
211,MPLID_S14_GRAND_FNL_D1_M1_G7,RRQ,Barats,Alpha,Faramis,Ixia,Mathilda,Team Liquid ID,"Terizla,Ling,Angela,Harith,Chou",0

In [320]:
df4 = pd.DataFrame(df3)
df4.rename(columns={'Red Team Heroes': 'Red Team EXP Laner'}, inplace=True)
df4.insert(9, 'Red Team Jungler', 0)
df4.insert(10, 'Red Team Midlaner', 0)
df4.insert(11, 'Red Team Gold Laner', 0)
df4.insert(12, 'Red Team Roamer', 0)
df4

,Match ID,Blue Team,Blue Team EXP Laner,Blue Team Jungler,Blue Team Midlaner,Blue Team Gold Laner,Blue Team Roamer,Red Team,Red Team EXP Laner,Red Team Jungler,Red Team Midlaner,Red Team Gold Laner,Red Team Roamer,Winner
0,MPLID_S14_GRP_W1_D1_M1_G1,Team Liquid ID,Edith,Julian,Luo Yi,Moskov,Minotaur,Fnatic Onic,"Arlott,Roger,Valentina,Harith,Chou",0,0,0,0,0
1,MPLID_S14_GRP_W1_D1_M1_G2,Fnatic Onic,Thamuz,Nolan,Va;entina,Harith,Minotaur,Team Liquid ID,"Arlott,Joy,Vexana,Roger,Edith",0,0,0,0,1
2,MPLID_S14_GRP_W1_D1_M2_G1,Dewa United Esport,Hylos,Julian,Valentina,Claude,Edith,EVOS Glory,"Ruby,Nolan,Vexana,Moskov,Khufra",0,0,0,0,1
3,MPLID_S14_GRP_W1_D1_M2_G2,Dewa United Esport,X.Borg,Julian,Valentina,Moskov,Arlott,EVOS Glory,"Hylos,Roger,Zask,Claude,Guinevere",0,0,0,0,0
4,MPLID_S14_GRP_W1_D1_M2_G3,Dewa United Esport,Paquito,Julian,Valentina,Moskov,Hylos,EVOS Glory,"X.Borg,Roger,Novaria,Harith,Guinevere",0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,MPLID_S14_GRAND_FNL_D1_M1_G3,Team Liquid ID,Benedetta,Alpha,Yve,Natan,Chip,RRQ,"Hilda,Bane,Zhuxin,Irithel,Gatotkaca",0,0,0,0,0
208,MPLID_S14_GRAND_FNL_D1_M1_G4,Team Liquid ID,Hylos,Suyou,Zhuxin,Beatrix,Khaleed,RRQ,"Hilda,Bane,Aurora,Natan,Mathilda",0,0,0,0,1
209,MPLID_S14_GRAND_FNL_D1_M1_G5,RRQ,Phoveus,Bane,Zhuxin,Beatrix,Jawhead,Team Liquid ID,"Khaleed,Alpha,Yve,Natan,Tigreal",0,0,0,0,1
210,MPLID_S14_GRAND_FNL_D1_M1_G6,Team Liquid ID,Phoveus,Ling,Angela,Lunox,Khaleed,RRQ,"Barats,Julian,Faramis,Irithel,Mathilda",0,0,0,0,1
211,MPLID_S14_GRAND_FNL_D1_M1_G7,RRQ,Barats,Alpha,Faramis,Ixia,Mathilda,Team Liquid ID,"Terizla,Ling,Angela,Harith,Chou",0,0,0,0,0

In [321]:
#loop for each row, adding heroes to new columns

df5 = pd.DataFrame(df4)

#change result column to 1 and 0. 1 means winning, 0 means losing
for i in range(len(df5)): 
    if (df5.loc[i,'Winner'] == 1):
        df5.loc[i,'Winner'] = 1
    elif (df5.loc[i,'Winner'] == 0):
        df5.loc[i,'Winner'] = 0
        
    data1=df5.loc[i,'Red Team EXP Laner']
    data1=data1.split(",")
    
    df5.loc[i,'Red Team EXP Laner']=data1[0].strip()
    df5.loc[i,'Red Team Jungler']=data1[1].strip()
    df5.loc[i,'Red Team Midlaner']=data1[2].strip()
    df5.loc[i,'Red Team Gold Laner']=data1[3].strip()
    df5.loc[i,'Red Team Roamer']=data1[4].strip()
    
df5

,Match ID,Blue Team,Blue Team EXP Laner,Blue Team Jungler,Blue Team Midlaner,Blue Team Gold Laner,Blue Team Roamer,Red Team,Red Team EXP Laner,Red Team Jungler,Red Team Midlaner,Red Team Gold Laner,Red Team Roamer,Winner
0,MPLID_S14_GRP_W1_D1_M1_G1,Team Liquid ID,Edith,Julian,Luo Yi,Moskov,Minotaur,Fnatic Onic,Arlott,Roger,Valentina,Harith,Chou,0
1,MPLID_S14_GRP_W1_D1_M1_G2,Fnatic Onic,Thamuz,Nolan,Va;entina,Harith,Minotaur,Team Liquid ID,Arlott,Joy,Vexana,Roger,Edith,1
2,MPLID_S14_GRP_W1_D1_M2_G1,Dewa United Esport,Hylos,Julian,Valentina,Claude,Edith,EVOS Glory,Ruby,Nolan,Vexana,Moskov,Khufra,1
3,MPLID_S14_GRP_W1_D1_M2_G2,Dewa United Esport,X.Borg,Julian,Valentina,Moskov,Arlott,EVOS Glory,Hylos,Roger,Zask,Claude,Guinevere,0
4,MPLID_S14_GRP_W1_D1_M2_G3,Dewa United Esport,Paquito,Julian,Valentina,Moskov,Hylos,EVOS Glory,X.Borg,Roger,Novaria,Harith,Guinevere,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,MPLID_S14_GRAND_FNL_D1_M1_G3,Team Liquid ID,Benedetta,Alpha,Yve,Natan,Chip,RRQ,Hilda,Bane,Zhuxin,Irithel,Gatotkaca,0
208,MPLID_S14_GRAND_FNL_D1_M1_G4,Team Liquid ID,Hylos,Suyou,Zhuxin,Beatrix,Khaleed,RRQ,Hilda,Bane,Aurora,Natan,Mathilda,1
209,MPLID_S14_GRAND_FNL_D1_M1_G5,RRQ,Phoveus,Bane,Zhuxin,Beatrix,Jawhead,Team Liquid ID,Khaleed,Alpha,Yve,Natan,Tigreal,1
210,MPLID_S14_GRAND_FNL_D1_M1_G6,Team Liquid ID,Phoveus,Ling,Angela,Lunox,Khaleed,RRQ,Barats,Julian,Faramis,Irithel,Mathilda,1
211,MPLID_S14_GRAND_FNL_D1_M1_G7,RRQ,Barats,Alpha,Faramis,Ixia,Mathilda,Team Liquid ID,Terizla,Ling,Angela,Harith,Chou,0

In [322]:
#Debugging
#if len(data1) == 5:
#    df4.loc[i, 'Red Team EXP Laner'] = data1[0].strip()
#    df4.loc[i, 'Red Team Jungler'] = data1[1].strip()
#    df4.loc[i, 'Red Team Midlaner'] = data1[2].strip()
#    df4.loc[i, 'Red Team Gold Laner'] = data1[3].strip()
#    df4.loc[i, 'Red Team Roamer'] = data1[4].strip()
#else:
#    print(f"Error di baris {i}: Jumlah hero tidak sesuai, yaitu {len(data1)} hero.")
#    print(f"Hero yang ada: {data1}")

In [323]:
df5.to_csv('MPL Draft Pick.csv', index=False)